### ISSUE TITLE
Test with auto-purge enabled restarts when stopped by the user

### ISSUE THREAD

**Issue by ppigazzini** [official-stockfish/fishtest#1158]
Issue reported on Discord about this test:
https://tests.stockfishchess.org/tests/view/61967fdccd645dc8291c88ab

Steps to replicate the issue:
1. create and run a test enabling `auto-purge` (also after the test creation)
2. stop the test by hand
3. the test auto-purges itself
4. the test auto unstops itself

Replicated on DEV raising the p-value to 0.5
https://dfts-0.pigazzini.it/tests/view/6198c612fded42b6bc0a480b

`auto-purge` should start only if the test is completed.

**Comment by BM123499** [comment]
Just to clarify, it doesn't need to be created as `auto-purge`, it just have to have `auto-purge` enabled.

**Comment by ppigazzini** [comment]
> Just to clarify, it doesn't need to be created as `auto-purge`, it just have to have `auto-purge` enabled.

Improved the issue description.

**Comment by vdbergh** [comment]
It can be fixed in various ways. One possibility is to set `auto_purge` to `False` if `stop_run()` is invoked as the result of user action, i.e. in the GUI or via `api_stop_run`.

Another option is to give `stop_run()` an optional argument `allow_auto_purge` (default `False`) which is set to `True` when `stop_run()` is invoked because a test is finished.

**Comment by vdbergh** [comment]
I think this is fixed (in any case the purge code has changed). Can be closed IMHO.
