### ISSUE TITLE
Priority Schema issue

### ISSUE THREAD

**Issue by peregrineshahin** [official-stockfish/fishtest#1923]
https://tests.stockfishchess.org/actions?max_actions=1&action=&user=&text=&before=1712177831.806576&run_id=
`The run object 6603d48c0ec64f0526c57826 does not validate: run['args']['priority'] (value:-1) is not in the interval [0,...]`

Using prio -1 is a common practice and is the onoly way to pause test

**Comment by peregrineshahin** [comment]
Worth noting that I see numbers as a type for priority, and numbers inherently can be negative.
an example of the worst language out there (JavaScript)
```
> typeof -5
<- 'number'
```

**Comment by vdbergh** [comment]
Ok. Another oversight. Of course priority can be negative. I'll fix it in PR #1916 .

**Comment by peregrineshahin** [comment]
I didn't realize that PR https://github.com/official-stockfish/fishtest/pull/1916 is running in Poduction...

**Comment by vdbergh** [comment]
`number` is equivalent to `union(int,float)` but it is implemented directly in the `vtjson` package for efficiency reasons (not sure if it is worth it). All the other types that are used in the schemas (such as `unumber`) are defined in `schemas.py`.

**Comment by vdbergh** [comment]
The validation code was originally written to simplify the validation of api calls via a convenient schema. Later I started documenting some of the data structures used by Fishtest (such as the humongous run object) via the same type of schemas. But of course such manually created documentation would be quickly outdated. Therefore I decided it would be a good idea to validate the actual runtime objects against the schemas so that any discrepancies would be quickly discovered. Ideally validation should be done by the database itself of course, although I am not sure if any database would have the same expressibility as vtjson.
