### ISSUE TITLE
Tests display incorrectly after server overload

### ISSUE THREAD

**Issue by dubslow** [official-stockfish/fishtest#2054]
https://discord.com/channels/435943710472011776/900771437177094156/1247992668101935134

The test page itself *appears* to be working fine, and still processing games and showing correct results.

However *other* pages which list tests, show a completely wrong summary per the images in the discord link.

two examples of such tests, whose main page seems fine but e.g. from the author page shows wrong summary (including showing as "Finished" when in fact still active):
https://tests.stockfishchess.org/tests/view/66608972c340c8eed7757d02
https://tests.stockfishchess.org/tests/view/666085b7c340c8eed7757cdd

Note the latter also has zombie tasks as well. Not sure if that's directly related

![image](https://github.com/official-stockfish/fishtest/assets/6127392/b863f5ed-12b3-4c33-aa21-dfd6a08c934a)

**Comment by vdbergh** [comment]
The new code that does the bookkeeping for counting the number of connections per ip address raised an exception which had the effect that the code for updating the aggregated data was not executed fully, creating inconsistencies.

Normally exceptions in Fishtest are not a problem but in this case they were.

The reason for the exception is currently not clear. One theory is that it was caused by a worker changing its ip address during the execution of a task. This possibility had not been accounted for, but now it has.

This is discussed in the comments to #2050

**Comment by dubslow** [comment]
yep just making sure you have all the symptoms in front of you

**Comment by vdbergh** [comment]
This can also be closed. It was fixed, but I don't remember in which PR.
