### ISSUE TITLE
Refactored locking algorithm in the worker

### ISSUE THREAD

**Issue by vdbergh** [official-stockfish/fishtest#2083]
The locking code in the worker is a bit messy, so I took it out and refactored it as a separate package https://pypi.org/search/?q=openlock . The GitHub repository is here https://github.com/vdbergh/openlock .

I would propose to include this in the worker. However the question is how? 

The package is basically two files. The main code is `openlock.py` and the unit tests are in `test_openlock.py`.

`test_openlock.py` should obviously go in the `tests` directory.

`openlock.py` can go in `packages`.

Is there a better solution?

I am a bit hesitant to include `openlock.py` in the root directory of the worker since for ages the worker has been basically three files.

**Comment by Disservin** [comment]
my two cents

- if this is developed completely separate from fishtest and is generic, everything should be in the packages
- if not, what is holding us back from
> I am a bit hesitant to include openlock.py in the root directory

? I think I asked pasquale some time ago if there were any issues with introducing new files since it would be a nice step in cleaning up some worker code

**Comment by vdbergh** [comment]
I am closing this since it does not generate a discussion.
